### ISSUE TITLE
检测字重的软件

### ISSUE THREAD

**Issue by MichaelPanPRC** [Magisk-Modules-Repo/chinesesimplified-font-completion#3]
对不起在这里打搅您，可是我没在其他地方找到您的联系方式。
可以上传或者贴一个 readme 中检测字重软件的链接么？
谢谢！

**Comment by CyanoHao** [comment]
这是整个 Android Studio 项目：
[CJKMultiWeight.zip](https://github.com/Magisk-Modules-Repo/chinesesimplified-font-completion/files/3043660/CJKMultiWeight.zip)

`app/build/outputs/apk/debug` 下面有一个 apk，但我不确定能不能直接装上去。

**Comment by MichaelPanPRC** [comment]
谢谢！

**Comment by MichaelPanPRC** [comment]
谢谢！
