### ISSUE TITLE
会导致状态栏的emoji变成框框

### ISSUE THREAD

**Issue by wewillchenoob** [Magisk-Modules-Repo/chinesesimplified-font-completion#4]
如题

**Comment by CyanoHao** [comment]
您是改了运营商标签吗？
![Screenshot_设置_20190412-233218](https://user-images.githubusercontent.com/14287996/56049166-75c95480-5d7b-11e9-9ff5-1a2864c4eb56.png)
但我这里改运营商标签是正常的。(Resurrection Remix 6.1)
能否发一下手机型号和 ROM 版本呢？

**Comment by wewillchenoob** [comment]
打错了…是浮动通知里的emoji，比如微信收到消息时里面包含emoji的话，就是框框。
机型：Mi MIX 2S
ROM：Pixel Experience

**Comment by CyanoHao** [comment]
我测试了一下，不确定这算不算是 “复现”。

短信的浮动通知里大多数 emoji 能正常显示；少量 emoji 不能显示，但这是因为 Noto Color Emoji 里面确实没画这些符号。
![Screenshot_Trebuchet_20190412-234703](https://user-images.githubusercontent.com/14287996/56051023-0013b780-5d80-11e9-88ad-27a9d6ac7ce7.png)

（微信对表情做了特殊处理，被转成文本了。）
![Screenshot_Trebuchet_20190412-234939](https://user-images.githubusercontent.com/14287996/56050725-343aa880-5d7f-11e9-9b4e-db55641438f6.png)

**Comment by wewillchenoob** [comment]
抱歉，我这边尝试了一下，无法复现了。应该不是你这个模块的问题。
