### ISSUE TITLE
请教一下这个方案会不会有字体偏移或者间距过大问题

### ISSUE THREAD

**Issue by laggardkernel** [Magisk-Modules-Repo/chinesesimplified-font-completion#6]
之前我一直用 RadarNyan 的方案来替换字体：掏空 Roboto 只留 metrics 保证替换的字体使用原来 Roboto 字体的 metric。

目前这个仓库应该是直接修改 Roboto 字体添加中文字形，不知道有没有上述偏移的问题，如[这里](https://sspai.com/post/58049)

-----

另外，咨询一个不大相关的问题。在仓库 README.md 展示中，使用此字体包后维基百科宋体页面的标题都是以宋体显示，但使用 simonsmh 的回落方案却显示的是黑体。这又是为什么？Android P 引入 `fallbackFor="serif"` 后，没有使用 `fallbackFor` 的字体仍是采用优先顺序回落吗？

**Comment by CyanoHao** [comment]
没有问题。替换字体的 metric 值和 Roboto 兼容。

另外可以用 [fontTools](https://github.com/fonttools/fonttools) 修改字体的 metric 值：
```python
from fontTools.ttLib import TTFont

# recalcBBoxes 很重要，避免保存的时候重算 bound box，又把 yMin、yMax 改回去了
font = TTFont("myfont.ttf", recalcBBoxes = False) 
ref = TTFont("Roboto-Regular.ttf")
scale = font['head'].unitsPerEm / ref['head'].unitsPerEm

# `head.yMin` 和 `head.yMax` 是导致间距过大的最重要因素
font['head'].yMin = round(ref['head'].yMin * scale)
font['head'].yMax = round(ref['head'].yMax * scale)

# 非 Apple 平台几乎不用 `hhea`，通常可以忽略
# font['hhea'].ascent = round(ref['hhea'].ascent * scale)
# font['hhea'].descent = round(ref['hhea'].descent * scale)
# font['hhea'].lineGap = round(ref['hhea'].lineGap * scale)

# `OS/2` 相关数值会对行高有所影响
font['OS/2'].usWinDescent = round(ref['OS/2'].usWinDescent * scale)
font['OS/2'].usWinAscent = round(ref['OS/2'].usWinAscent * scale)

font['OS/2'].sTypoAscender = round(ref['OS/2'].sTypoAscender * scale)
font['OS/2'].sTypoDescender = round(ref['OS/2'].sTypoDescender * scale)
font['OS/2'].sTypoLineGap = round(ref['OS/2'].sTypoLineGap * scale)

font.save("output.ttf")
```
-----
“serif” fallback 到黑体是 WebView 的问题，WebView 不遵守 Android 的 fonts.xml 里的设定。simonsmh 的方案在 Android 系统 UI 上面是正常的。

说一句略有夸张的话，Blink 及其前身 WebKit 就没把字体弄对过……
Chrome 在 Windows 上一度把中易宋体设为简体中文的 “sans-serif”。而在英语版 Windows 上，通过适当的设置，Segoe UI 字体的汉字会 fallback 到微软雅黑显示；但直到今天，Chrome 仍然是 Segoe UI 配微软正黑体……

**Comment by laggardkernel** [comment]
metric 值我在你的字体生成脚本仓库中看到声明了。也谢谢你对于 Webview 这种诡异行为的解答。
